# Goldsky Mirror Pipeline for Lumen Later BNPL Protocol
# Streams Soroban contract events to PostgreSQL
#
# Setup:
#   1. goldsky login
#   2. goldsky secret create LUMEN_LATER_DB --value "postgresql://..."
#   3. goldsky pipeline apply ./indexer/pipeline.yaml
#   4. goldsky pipeline start lumen-later-events
#
# Docs: https://docs.goldsky.com/chains/stellar

apiVersion: 3
name: lumen-later-events
resource_size: s

sources:
  # Stellar testnet events dataset
  stellar_events:
    type: dataset
    dataset_name: stellar_testnet.events
    version: 1.0.0
    start_at: latest  # Use 'latest' for testnet (resets every ~3 months)

transforms:
  # Filter only our contract events
  filter_bnpl_contracts:
    sql: |
      SELECT
        id,
        contract_id,
        topic,
        data,
        ledger_sequence as ledger,
        transaction_hash as tx_hash,
        closed_at as timestamp
      FROM stellar_events
      WHERE contract_id IN (
        'CC7KPNSQWP2FKOAXMDI7LN7FREPJNQM44QO4VAL5WDDCAV4OC2YDGOWY',
        'CDDIYSWIAPZALYJUT47YY33NTBYY6KXYXBMU6AY4KQ6FZJ7N3JCKPBEB',
        'CBNOIIPYSYNBH477KUBOX5VRWUIW2PLDF4TE52GGYWRKSQM4BMD5GHK2'
      )
    primary_key: id

sinks:
  # Stream to PostgreSQL
  postgres:
    type: postgres
    table: contract_events
    schema: public
    secret_name: LUMEN_LATER_DB
    from: filter_bnpl_contracts
