# Goldsky Mirror Pipeline for Lumen Later BNPL Protocol
# Streams Soroban contract events to PostgreSQL
#
# Setup:
#   1. goldsky login
#   2. goldsky secret create LUMEN_LATER_DB --value '{"type":"jdbc","protocol":"postgresql",...}'
#   3. goldsky pipeline apply ./indexer/pipeline.yaml
#   4. goldsky pipeline start lumen-later-events
#
# Docs: https://docs.goldsky.com/chains/stellar

apiVersion: 3
name: lumen-later-events
resource_size: s

sources:
  # Stellar ledgers dataset (contains nested transactions and events)
  stellar_ledgers:
    type: dataset
    dataset_name: stellar.ledgers
    version: 3.1.0
    start_at: latest

transforms:
  # Flatten transactions from ledgers
  flatten_transactions:
    sql: |
      SELECT
        l.sequence as ledger_sequence,
        l.closed_at,
        t.*
      FROM stellar_ledgers l
      CROSS JOIN UNNEST(l.transactions) as t
    primary_key: transaction_hash

  # Flatten events from transactions and filter our contracts
  filter_bnpl_events:
    sql: |
      SELECT
        e.id,
        e.contract_id,
        e.topics as topic,
        e.data,
        ft.ledger_sequence as ledger,
        ft.transaction_hash as tx_hash,
        ft.closed_at as event_timestamp
      FROM flatten_transactions ft
      CROSS JOIN UNNEST(ft.events) as e
      WHERE e.contract_id IN (
        'CC7KPNSQWP2FKOAXMDI7LN7FREPJNQM44QO4VAL5WDDCAV4OC2YDGOWY',
        'CDDIYSWIAPZALYJUT47YY33NTBYY6KXYXBMU6AY4KQ6FZJ7N3JCKPBEB',
        'CBNOIIPYSYNBH477KUBOX5VRWUIW2PLDF4TE52GGYWRKSQM4BMD5GHK2'
      )
      AND e.type = 'contract'
    primary_key: id

sinks:
  # Stream to PostgreSQL
  postgres:
    type: postgres
    table: contract_events
    schema: public
    secret_name: LUMEN_LATER_DB
    from: filter_bnpl_events
