# Goldsky Mirror Pipeline for Lumen Later BNPL Protocol
# Streams Soroban contract events to PostgreSQL + Webhook processing
#
# Setup:
#   1. goldsky login
#   2. goldsky secret create --name LUMEN_LATER_DB --value '{"type":"jdbc",...}'
#   3. Update WEBHOOK_URL below (use ngrok for local testing)
#   4. goldsky pipeline apply ./indexer/pipeline.yaml
#
# Docs: https://docs.goldsky.com/chains/stellar

apiVersion: 3
name: lumen-later-events
resource_size: s

sources:
  stellar_events:
    type: dataset
    dataset_name: stellar_testnet.events
    version: 3.0.0
    start_at: earliest

transforms:
  filter_bnpl_contracts:
    sql: |
      SELECT *
      FROM stellar_events
      WHERE contract_id IN (
        'CA3T77DH6B7CVAR24XP4BX6GLQOMVHOWRXH6D6EXYAPOYNMCCRZSG5YO',
        'CBHXULLUD7EDNSVM23HFO6ZK3UETZSPGGSVZ4W3ANH2SRLEDBT5GNVUB',
        'CC64364OA6BFTMDJYN2IPZV2RQDC2O742DJYKWN6TA3CUA44DFJE3K43'
      )
    primary_key: id

  # Webhook handler to process events into parsed_bills/parsed_merchants tables
  process_events:
    type: handler
    from: filter_bnpl_contracts
    primary_key: id
    url: https://b8236908cd29.ngrok-free.app/api/indexer/webhook

sinks:
  # Raw events backup
  postgres:
    type: postgres
    table: contract_events
    schema: public
    secret_name: LUMEN_LATER_DB
    from: process_events
