# Goldsky Mirror Pipeline for Lumen Later BNPL Protocol
# Streams Soroban contract events to PostgreSQL + Webhook processing
#
# Setup:
#   1. goldsky login
#   2. goldsky secret create --name LUMEN_LATER_DB --value '{"type":"jdbc",...}'
#   3. goldsky secret create --name WEBHOOK_SECRET --value '{"type":"httpauth","secretKey":"x-goldsky-secret","secretValue":"<secret>"}'
#   4. goldsky pipeline apply ./indexer/pipeline.yaml
#
# Docs: https://docs.goldsky.com/chains/stellar

apiVersion: 3
name: lumen-later-events
resource_size: s

sources:
  stellar_events:
    type: dataset
    dataset_name: stellar_testnet.events
    version: 3.0.0
    start_at: earliest

transforms:
  filter_bnpl_contracts:
    sql: |
      SELECT *
      FROM stellar_events
      WHERE contract_id IN (
        'CDMO6H62M3DRFBJK64FJMWRWQX5KII4LOGTFPPCZX5TI4HZIZXUBJYCR',
        'CAX6EIH57YFHFLMIOT52XHB6NQO3DXEDTRV2EUNR7UMCUY43OC6INZBZ',
        'CAUPXJIGAV4PLNWJIVYTDRMS7YCEQXSQ7GASJWSJT6EPIKZ3TPWUKXT5'
      )
    primary_key: id

  # Webhook handler to process events into parsed_bills/parsed_merchants tables
  # Sends x-goldsky-secret header with WEBHOOK_SECRET value for authentication
  process_events:
    type: handler
    from: filter_bnpl_contracts
    primary_key: id
    url: https://www.lumenlater.org/api/indexer/webhook
    secret_name: WEBHOOK_SECRET

sinks:
  # Raw events backup
  postgres:
    type: postgres
    table: contract_events
    schema: public
    secret_name: LUMEN_LATER_DB
    from: process_events
