# Goldsky Mirror Pipeline for Lumen Later BNPL Protocol
# Streams Soroban contract events to PostgreSQL
#
# Setup:
#   1. goldsky login
#   2. goldsky secret create --name LUMEN_LATER_DB --value '{"type":"jdbc",...}'
#   3. goldsky pipeline apply ./indexer/pipeline.yaml
#
# Docs: https://docs.goldsky.com/chains/stellar

apiVersion: 3
name: lumen-later-events
resource_size: s

sources:
  stellar_events:
    type: dataset
    dataset_name: stellar_testnet.events
    version: 3.0.0
    start_at: earliest

transforms:
  filter_bnpl_contracts:
    sql: |
      SELECT *
      FROM stellar_events
      WHERE contract_id IN (
        'CARXH5FIHDJSKPNJOZXLGXKCWHZWYWNAMFGUPTQ4IMYIQ7YXNT3LRXOF',
        'CDY247U3DLKHU3TPRGM2G2MDQLSHZLZ2WHSUDBGHMKR534BGX334F2B2',
        'CDAIS5ZE6MA4TKFXFEXUQ2HA6Z2S4DI2PHOLIBXEMNVQ3CIQNMJWJBAY'
      )
    primary_key: id

sinks:
  postgres:
    type: postgres
    table: contract_events
    schema: public
    secret_name: LUMEN_LATER_DB
    from: filter_bnpl_contracts
