// Auto-generated contract IDs

export const CONTRACT_IDS = {
  USDC_TOKEN: 'CDAIS5ZE6MA4TKFXFEXUQ2HA6Z2S4DI2PHOLIBXEMNVQ3CIQNMJWJBAY',
  LP_TOKEN: 'CDY247U3DLKHU3TPRGM2G2MDQLSHZLZ2WHSUDBGHMKR534BGX334F2B2',
  BNPL_CORE: 'CARXH5FIHDJSKPNJOZXLGXKCWHZWYWNAMFGUPTQ4IMYIQ7YXNT3LRXOF',
} as const;
